# Generated by Django 5.2.4 on 2025-07-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='item',
            field=models.CharField(choices=[('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('CPU', 'CPU'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Printer', 'Printer'), ('Monitor', 'Monitor'), ('Other', 'Other')], max_length=50),
        ),
    ]
