# Generated by Django 5.2.4 on 2025-07-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterModelOptions(
            name='complaintimage',
            options={'verbose_name': 'Complaint Image', 'verbose_name_plural': 'Complaint Images'},
        ),
        migrations.AlterModelOptions(
            name='jobcard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Card', 'verbose_name_plural': 'Job Cards'},
        ),
        migrations.AddField(
            model_name='jobcard',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='item',
            field=models.CharField(choices=[('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('CPU', 'CPU'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Printer', 'Printer'), ('Monitor', 'Monitor'), ('Other', 'Other')], max_length=50),
        ),
    ]
