# Generated by Django 5.2.4 on 2025-07-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcardapp', '0002_alter_complaint_options_alter_complaintimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='complaintimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobcard',
            options={'ordering': ['-created_at']},
        ),
    ]
